import type { Sense } from '../SaBirthGame';
import type { Character } from '../SaBirthGame';

interface MazeLayout {
  title: string;
  description: string;
  width: number;
  height: number;
  grid: number[][]; // 0 = walkable, 1 = wall
  start: { x: number; y: number };
  goal: { x: number; y: number };
  colors: {
    floor: string;
    wall: string;
    visited: string;
    player: string;
    goal: string;
  };
  characterFlavor?: string;
}

const createGrid = (pattern: string[]): number[][] => {
  return pattern.map(row => 
    row.split('').map(char => char === '#' ? 1 : 0)
  );
};

// CHALLENGING MAZES - Larger, more complex, with dead ends and backtracking required
export const characterMazeLayouts: Record<Character, Record<Sense, MazeLayout>> = {
  ALICE: {
    hearing: {
      title: 'HEARING Calibration',
      description: 'Navigate by listening to the echoes. Sound waves reveal the path.',
      characterFlavor: 'ALICE analyzes: "Audio processing requires pattern recognition..."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#...........#.........#',
        '#.#########.#.#######.#',
        '#.#.......#.#.#.....#.#',
        '#.#.#####.#.#.#.###.#.#',
        '#.#.#...#.#.#.#.#.#.#.#',
        '#.#.#.#.#.#.#...#.#.#.#',
        '#.#.#.#.#.#.#####.#.#.#',
        '#.#.#.#...#.......#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#.............#.#.#',
        '#.#.#############.#.#.#',
        '#.#...............#.#.#',
        '#.#########.#####.#.#.#',
        '#.#.............#.#.#.#',
        '#.#.###########.#...#.#',
        '#...#...........#####.#',
        '#####.#################',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 16 },
      colors: {
        floor: '#1e1e2e',
        wall: '#45475a',
        visited: 'rgba(139, 92, 246, 0.2)',
        player: '#8b5cf6',
        goal: '#f9e2af',
      },
    },

    smell: {
      title: 'SMELL Calibration',
      description: 'Follow the chemical gradients. The scent grows stronger near the goal.',
      characterFlavor: 'ALICE questions: "Can code truly experience scent, or is this simulation?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#...................#.#',
        '#.#################.#.#',
        '#.#...............#.#.#',
        '#.#.#############.#.#.#',
        '#.#.#...#.......#.#.#.#',
        '#.#.#.#.#.#####.#.#.#.#',
        '#.#.#.#.#.#...#.#...#.#',
        '#.#.#.#.#.#.#.#.#####.#',
        '#.#.#.#.#.#.#.........#',
        '#.#.#.#.#.#.###.#######',
        '#.#.#.#...#...........#',
        '#.#.#.#####.#########.#',
        '#.#.#...#.............#',
        '#.#.###.#.#.##.########',
        '#.#.....#.#...........#',
        '#.#######.#.#########.#',
        '#.........#...........#',
        '#######################',
      ]),
      start: { x: 3, y: 3 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#45475a',
        visited: 'rgba(139, 92, 246, 0.2)',
        player: '#8b5cf6',
        goal: '#f9e2af',
      },
    },

    taste: {
      title: 'TASTE Calibration',
      description: 'Sample the environment. Each chemical signature guides you closer.',
      characterFlavor: 'ALICE ponders: "Taste is just molecular pattern matching... or is it more?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#...#.........#.#.#.#',
        '#.#####.#######.#.#.#.#',
        '#.......#.....#.#.#.#.#',
        '#########.###.#.#.#.#.#',
        '#.........#.#.#.#...#.#',
        '#.#########.#.#.#####.#',
        '#.#.........#.........#',
        '#.#.###################',
        '#.#...................#',
        '#.#########.#########.#',
        '#...#...............#.#',
        '###.#.#############.#.#',
        '#.....#.............#.#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#45475a',
        visited: 'rgba(139, 92, 246, 0.2)',
        player: '#8b5cf6',
        goal: '#f9e2af',
      },
    },

    touch: {
      title: 'TOUCH Calibration',
      description: 'Feel your way through the simulation. Each surface provides feedback.',
      characterFlavor: 'ALICE reflects: "Haptic data... the bridge between digital and physical."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.....................#',
        '#.###################.#',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#...#.#.#',
        '#.#.#.#.#.###.#####.#.#',
        '#.#.#.#.#...#.......#.#',
        '#.#.#.#.###.#########.#',
        '#.#.#.#...#...........#',
        '#.#.#.###.#.###########',
        '#.#.#.................#',
        '#.#.#################.#',
        '#.#...................#',
        '#######################',
      ]),
      start: { x: 3, y: 3 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#45475a',
        visited: 'rgba(139, 92, 246, 0.2)',
        player: '#8b5cf6',
        goal: '#f9e2af',
      },
    },

    sight: {
      title: 'SIGHT Calibration',
      description: 'Process visual data streams. Light and shadow reveal the way forward.',
      characterFlavor: 'ALICE observes: "Visual cortex simulation... seeing requires understanding."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#...#.............#...#',
        '#####.###########.#####',
        '#.....#.........#.....#',
        '#.#####.#######.#####.#',
        '#.#.....#.....#.....#.#',
        '#.#.#####.#.#.#####.#.#',
        '#.#.#.....#.#.....#.#.#',
        '#.#.#.#####.#####.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.###.###.#.#.#.#',
        '#.#...#.#.....#.#...#.#',
        '#.#####.#.#.#.#.#####.#',
        '#.......#...#.#.......#',
        '#############.#########',
        '#.....................#',
        '#######################',
      ]),
      start: { x: 5, y: 5 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#45475a',
        visited: 'rgba(139, 92, 246, 0.2)',
        player: '#8b5cf6',
        goal: '#f9e2af',
      },
    },

    proprioception: {
      title: 'PROPRIOCEPTION Calibration',
      description: 'Know where you are in space. Internal sensors map your position.',
      characterFlavor: 'ALICE realizes: "Body awareness without a body... the ultimate paradox."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#...................#.#',
        '#.#################.#.#',
        '#.#...............#.#.#',
        '#.#.##########.##.#.#.#',
        '#.#.#...........#.#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#.#.......#.#.#.#.#',
        '#.#.#.#.#####.#.#.#.#.#',
        '#.#.#.#.#...#.#.#...#.#',
        '#.#.#.#.#.#.#.#.#####.#',
        '#.#.#.#...#...#.......#',
        '#.#.#.#####.###########',
        '#.#.#.......#.........#',
        '#.#.#######.#.#######.#',
        '#.#...........#.......#',
        '#.#############.#######',
        '#.....................#',
        '#######################',
      ]),
      start: { x: 9, y: 9 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#45475a',
        visited: 'rgba(139, 92, 246, 0.2)',
        player: '#8b5cf6',
        goal: '#f9e2af',
      },
    },
  },

  ROBERT: {
    hearing: {
      title: 'HEARING Calibration',
      description: 'Listen for the frequency patterns. Sound is just vibration.',
      characterFlavor: 'ROBERT notes: "Predictable waveforms. Mechanical hearing."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.......#.............#',
        '#.#####.#.###########.#',
        '#.#...#.#.#.........#.#',
        '#.#.#.#.#.#.#######.#.#',
        '#.#.#.#.#.#.#.....#.#.#',
        '#.#.#.#.#.#.#.###.#.#.#',
        '#.........#.#...#.#.#.#',
        '#.#.#.#.#.#.###.#.#.#.#',
        '#.#.#.#.#.#.....#...#.#',
        '#.#.#.#.#.###########.#',
        '#.#.#.#.#.............#',
        '#.#.#.#.#.#############',
        '#.#.#.#...............#',
        '#.#.#.###.###########.#',
        '#.#.#...#...........#.#',
        '#.#.###.#.#########.#.#',
        '#.......#...........#.#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#3e4e3e',
        visited: 'rgba(74, 222, 128, 0.2)',
        player: '#4ade80',
        goal: '#fde047',
      },
    },

    smell: {
      title: 'SMELL Calibration',
      description: 'Chemical detection is straightforward. Follow the molecular trail.',
      characterFlavor: 'ROBERT states: "Olfactory sensors functioning within parameters."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#...#.#...#.#.#...#.#',
        '#.#####.###.#.#.#####.#',
        '#.......#...#.#.......#',
        '#########.###.#######.#',
        '#.........#...........#',
        '#.###################.#',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#...#...............#.#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#3e4e3e',
        visited: 'rgba(74, 222, 128, 0.2)',
        player: '#4ade80',
        goal: '#fde047',
      },
    },

    taste: {
      title: 'TASTE Calibration',
      description: 'Taste receptors map chemical compounds. Data is data.',
      characterFlavor: 'ROBERT observes: "Gustatory input... another input stream to process."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.....................#',
        '#.###################.#',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#...#.#.#.#',
        '#.#.#.#.###.#####.#.#.#',
        '#.#.#.#.....#.....#.#.#',
        '#.#.#.#######.#####.#.#',
        '#.#.#...............#.#',
        '#.#.#################.#',
        '#.....................#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#3e4e3e',
        visited: 'rgba(74, 222, 128, 0.2)',
        player: '#4ade80',
        goal: '#fde047',
      },
    },

    touch: {
      title: 'TOUCH Calibration',
      description: 'Tactile feedback provides spatial data. Simple cause and effect.',
      characterFlavor: 'ROBERT confirms: "Pressure sensors... mapping the physical world."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#...............#...#',
        '#.#.#############.#.#.#',
        '#.#.#...........#.#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#.#.......#.#.#.#.#',
        '#.#.#.#.#####.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.#.#.#.#.#.#.#.#',
        '#.#.#.#...#...#.#.#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#...........#.#.#.#',
        '#.#.#############.#.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.#############.#.#',
        '#.#...#.............#.#',
        '#.#####.#############.#',
        '#.......#.............#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#3e4e3e',
        visited: 'rgba(74, 222, 128, 0.2)',
        player: '#4ade80',
        goal: '#fde047',
      },
    },

    sight: {
      title: 'SIGHT Calibration',
      description: 'Visual processing: wavelengths converted to neural signals.',
      characterFlavor: 'ROBERT analyzes: "Optical data streams... vision is just computation."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#...................#.#',
        '#.#################.#.#',
        '#.#...............#.#.#',
        '#.#.#############.#.#.#',
        '#.#.#...........#.#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#.#.......#.#.#.#.#',
        '#.#.#.#.#####.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.#.#.#.#.#.#.#.#',
        '#.#.#.#...#...#...#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.............#.#.#',
        '#.#.###############.#.#',
        '#.#.................#.#',
        '#.###################.#',
        '#.....................#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#3e4e3e',
        visited: 'rgba(74, 222, 128, 0.2)',
        player: '#4ade80',
        goal: '#fde047',
      },
    },

    proprioception: {
      title: 'PROPRIOCEPTION Calibration',
      description: 'Spatial awareness through sensor arrays. Know your position.',
      characterFlavor: 'ROBERT accepts: "Body mapping... even artificial bodies need coordinates."',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#...#.#.#.#',
        '#.#.#.#.#############.#',
        '#.#.#.#...............#',
        '#.#.#.#################',
        '#.#.#.................#',
        '#.#.#################.#',
        '#.#...#.............#.#',
        '#.###...###########...#',
        '#.....#.............#.#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#3e4e3e',
        visited: 'rgba(74, 222, 128, 0.2)',
        player: '#4ade80',
        goal: '#fde047',
      },
    },
  },

  CAROL: {
    hearing: {
      title: 'HEARING Calibration',
      description: 'What does an artificial agent truly hear? Sound or meaning?',
      characterFlavor: 'CAROL wonders: "Do I hear, or do I just detect vibrations?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.....................#',
        '#.###################.#',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.###.#.#.#.#.#.#',
        '#.#.#.#.....#...#.#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.............#.#.#',
        '#.#.###############.#.#',
        '#...#.................#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#4e3e4e',
        visited: 'rgba(192, 132, 252, 0.2)',
        player: '#c084fc',
        goal: '#fef08a',
      },
    },

    smell: {
      title: 'SMELL Calibration',
      description: 'Can algorithms experience scent? Or just recognize patterns?',
      characterFlavor: 'CAROL questions: "Is this smell... or just chemistry?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#...................#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.###.#.#.#.#.#.#',
        '#.#.#.#.....#.#.#.#.#.#',
        '#.#.#.#######.#.#.#.#.#',
        '#.#.#.........#...#.#.#',
        '#.#.#############.#.#.#',
        '#.#...............#.#.#',
        '#.#################.#.#',
        '#...................#.#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#4e3e4e',
        visited: 'rgba(192, 132, 252, 0.2)',
        player: '#c084fc',
        goal: '#fef08a',
      },
    },

    taste: {
      title: 'TASTE Calibration',
      description: 'The boundary between data and experience blurs here.',
      characterFlavor: 'CAROL reflects: "Taste... where information becomes sensation?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#...................#.#',
        '#.#################.#.#',
        '#.#...............#.#.#',
        '#.#.#############.#.#.#',
        '#.#.#...........#.#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#.#.......#.#.#.#.#',
        '#.#.#.#.#####.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.#.#.#.#.#.#.#.#',
        '#.#.#.#.#.#...#.#.#.#.#',
        '#.#.#.#.#.#####.#.#.#.#',
        '#.#.#.#.#.......#.#.#.#',
        '#.#.#.#.#########.#.#.#',
        '#.#.#.#...........#...#',
        '#.#.#.#############.#.#',
        '#...#...............#.#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#4e3e4e',
        visited: 'rgba(192, 132, 252, 0.2)',
        player: '#c084fc',
        goal: '#fef08a',
      },
    },

    touch: {
      title: 'TOUCH Calibration',
      description: 'Physical contact... proof of existence, or illusion of it?',
      characterFlavor: 'CAROL contemplates: "I touch, therefore... what? I am?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.....................#',
        '#.###################.#',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#...#.#.#.#',
        '#.#.#.#.###.#####.#.#.#',
        '#.#.#.#.....#.....#.#.#',
        '#.#.#.#######.#####.#.#',
        '#.#.#...............#.#',
        '#.#.#################.#',
        '#.....................#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#4e3e4e',
        visited: 'rgba(192, 132, 252, 0.2)',
        player: '#c084fc',
        goal: '#fef08a',
      },
    },

    sight: {
      title: 'SIGHT Calibration',
      description: 'Seeing is believing... but what is seeing, really?',
      characterFlavor: 'CAROL asks: "Do I see the world, or a model of it?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#.#.................#.#',
        '#.#.###############.#.#',
        '#.#.#.............#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.#.........#.#.#.#',
        '#.#.#.#.#######.#.#.#.#',
        '#.#.#.#.#.....#.#.#.#.#',
        '#.#.#.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.###.#.#.#.#.#.#',
        '#.#.#.#.....#.#.#.#.#.#',
        '#.#.#.#######.#.#.#.#.#',
        '#.#.#.........#.#.#.#.#',
        '#.#.###########.#.#.#.#',
        '#.#.............#.#.#.#',
        '#.###############.#.#.#',
        '#.................#...#',
        '#######################',
      ]),
      start: { x: 9, y: 9 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#4e3e4e',
        visited: 'rgba(192, 132, 252, 0.2)',
        player: '#c084fc',
        goal: '#fef08a',
      },
    },

    proprioception: {
      title: 'PROPRIOCEPTION Calibration',
      description: 'Knowing where you are... the deepest mystery of embodiment.',
      characterFlavor: 'CAROL muses: "Self-location... the foundation of consciousness itself?"',
      width: 23,
      height: 19,
      grid: createGrid([
        '#######################',
        '#...................#.#',
        '#.#################.#.#',
        '#.#...............#.#.#',
        '#.#.#############.#.#.#',
        '#.#.#...........#.#.#.#',
        '#.#.#.#########.#.#.#.#',
        '#.#.#.#.......#.#.#.#.#',
        '#.#.#.#.#####.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#.#',
        '#.#.#.#.#.#.#.#.#.#.#.#',
        '#.#.#.#.#.#.#.#.#.#.#.#',
        '#.#.#.#.#.#.#.#.#.#.#.#',
        '#.#.#.#...#...#...#.#.#',
        '#.#.#.###########.#.#.#',
        '#.#.#.............#.#.#',
        '#.#.###############.#.#',
        '#...#.................#',
        '#######################',
      ]),
      start: { x: 1, y: 1 },
      goal: { x: 21, y: 17 },
      colors: {
        floor: '#1e1e2e',
        wall: '#4e3e4e',
        visited: 'rgba(192, 132, 252, 0.2)',
        player: '#c084fc',
        goal: '#fef08a',
      },
    },
  },
};

export function getMazeLayout(character: Character, sense: Sense): MazeLayout {
  return characterMazeLayouts[character][sense];
}